version: 2

models:
    - name: D_Element
      description: "A Elements dbt model"
      columns:
          - name: D_element_id
            description: "Unique id of Element"
            tests:
                - unique
                - not_null
          - name: element_name
            description: "Name of Element"
            tests:
                - unique
                - not_null
          - name: element_acronym
            description: "Acronym  of Element"
            tests:
                - unique
                - not_null